version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "chore[deps]"
    labels:
      - chore
    assignees:
      - LexisNexis-RBA/iog-terraform-owners
